version: '3.8'
services:

  #Apache Service
  webserver:
    hostname: httpd
    image: httpd:2.4.43
    container_name: webserver
    depends_on:
      - app
    volumes:
      - "./etc/apache2/:/etc/apache2/"
    restart: unless-stopped
    tty: true
    networks:
      - net

  #MySQL Service
  db:
    hostname: db
    container_name: db
    image: 'yobasystems/alpine-mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'db'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'db'
      MYSQL_PASSWORD: 'db'
    volumes:
      - dbdata:/var/lib/mysql/ # allows you to stop and restart the db service without losing data
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - net

  #PHP Service
  app:
    hostname: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: "mensa"
        APP_REPO: "https://github.com/vslcatena/mensa.git"
    container_name: app
    depends_on: 
      - db    
    restart: unless-stopped
    tty: true
    environment:
      - SERVICE_NAME: app
      - SERVICE_TAGS: dev
      - APP_NAME: mensa
      - APP_REPO: https://github.com/vslcatena/mensa.git
    ports:
      - 1234:8080
    volumes:
      - ./laravel-app:/var/www/laravel
      - "./etc/php/local.ini:/usr/local/etc/php/conf.d/local.ini"
    networks:
      - net
    command: bash -c "
             if ls /var/www/${APP_NAME} 2> /tmp/test.txt; then mv /var/www/${APP_NAME} /var/www/laravel/${APP_NAME} ; else echo 0; fi
             && cd /var/www/laravel/${APP_NAME}
             && php artisan migrate
             && php artisan serve --port=8080 --host=app"

#Docker Networks
networks:
  net:
    driver: bridge
volumes:
  dbdata:
    driver: local
  laravel-app:
    driver: local
